name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip<=25.3
  - pip:
      - mlflow
      - cloudpickle
      - numpy
      - pandas
      - pyarrow
      - scikit-learn
      - scipy
      - joblib
      - matplotlib